### ISSUE TITLE
Error with skcb_paste()

### ISSUE THREAD

**Issue by Murreey** [jb-aero/SKCompat#24]
I'm getting a console error skcb_paste() after updating to 1.9 and the lastest(ish) SKCompat versions.

Function's only being passed a location array, which used to run fine.

Error: https://gist.github.com/anonymous/a571c0bd64646d9199f5c5a190978d6c 

I tried passing in an empty array as the optionsArray argument but it still gives the same thing error. I'm not passing a name into the skcb_load() before, which seems to be something to do with it? Still happens if I do pass a name into it though.

Running CommandHelper build #3110, SKCompat #26 and CHWorldGuard #22.

Thanks!

**Comment by jb-aero** [comment]
You are using FastAsyncWorldEdit or whatever it is called, which appears to change how worldedit works using reflection. I will check if there is anything I can do differently, but from the error FAWE is causing the error when WE does what I tell it.

Apologies for not noticing this issue being submitted earlier. In fact I only noticed it now because #26 was opened. For simplicity's sake, I'll use that one for tracking since it is more recent.
